version: '3.7'

services:
  client:
    build: ./docker/client
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: ['npm', 'run', 'dev']
    container_name: 'client'

  server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w ranek.json
    ports:
      - "3000:3000"
    volumes:
      - ./api:/data
    restart: always